name = "orbs"
version = "0.2.0"
license = "license"
author = "Tomohiro Degawa"
maintainer = "degawa.tomohiro@gmail.com"
copyright = "Copyright 2023, Tomohiro Degawa"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[preprocess]
[preprocess.cpp]

[dependencies]
stdlib = '*'
bstrith = {git = "https://github.com/degawa/bstrith.git"}

[dev-dependencies]
test-drive = { git="https://github.com/fortran-lang/test-drive" }
testdrive_util = { git="https://github.com/degawa/testdrive_util" }
fassert = { git = "https://github.com/degawa/fassert"}
enclose = { git = "https://github.com/degawa/enclose"}
